### ISSUE TITLE
Cloud config client - class not found when running in PCF and rabbit is not on the classpath

### ISSUE THREAD

**Issue by bodin** [pivotal-cf/spring-cloud-services-starters#20]
Using 1.6.2 in PCF, I am getting a 'class not found' exception when rabbit is not on the class path.

```
compile 'io.pivotal.spring.cloud:spring-cloud-services-starter-config-client:1.6.2.RELEASE'
```

```
java.lang.NoClassDefFoundError: org/springframework/amqp/rabbit/connection/ConnectionFactory
 at io.pivotal.spring.cloud.config.java.ServiceInfoPropertySourceAdapter.appIsBoundToRabbitMQ(ServiceInfoPropertySourceAdapter.java:91)
```
```
private boolean appIsBoundToRabbitMQ() {
	boolean hasEnvironmentBinding = environment.containsProperty("spring.rabbitmq.host") &&
			!environment.getProperty("spring.rabbitmq.host").equals("localhost");

	//Connection Factory is not on the class path, this line is causing the problem
	boolean hasCloudBinding = !cloud.getServiceInfos(ConnectionFactory.class).isEmpty();
	return hasEnvironmentBinding || hasCloudBinding;
}
```

**Comment by spikymonkey** [comment]
Hi @bodin, thanks for the report. This is my bad unfortunately - we just noticed that this slipped through the cracks and into 1.6.2 too. We have a fix and we're working on getting that out in a 1.6.3 release out asap. In the meantime, I think sticking with 1.6.1 until we can get the fix published is probably your best bet.

Sorry for the inconvenience!

**Comment by bodin** [comment]
Cool - thanks!

**Comment by spikymonkey** [comment]
Thanks to @habuma, 1.6.3 is out now and contains the fix for this issue. Thanks again for the report @bodin!

**Comment by bodin** [comment]
I an confirm this is working now - thanks for the quick fix!

**Comment by spikymonkey** [comment]
Great!
